name: CI Stage

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create env file
        run: make config-env
  
      - name: Build server
        run: make docker-build

      - name: Runserver
        run: make runsever

      - name: Run Flake8
        run: docker-compose exec -T backend pipenv run flake8

      - name: Run tests and coverage
        run: docker-compose exec -T backend pipenv run pytest --cov
